run:
  concurrency: 1

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - gomnd
  fast: true

linters-settings:
  unused:
    skip-regexp: .+_test\.go

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - deadcode
        - dogsled
        - unparam
        - unused
