linters:
  enable-all: true
  disable:
    - gci
    - maligned # deprecated
    - interfacer # deprecated

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - exhaustivestruct
        - gochecknoglobals

  include:
    - EXC0002 # disable excluding of issues about comments from golint
